#!/usr/bin/python3
import sys


def gcd(a, b):
    """Find the greatest common divisor of two numbers."""
    while b:
        a, b = b, a % b
    return a


def pollard_rho(n):
    """Find a non-trivial factor of a number using Pollard's rho algorithm."""
    if n % 2 == 0:
        return 2
    x = 2
    y = 2
    d = 1
    def f(x): return (x ** 2 + 1) % n
    while d == 1:
        x = f(x)
        y = f(f(y))
        d = gcd(abs(x - y), n)
    return d


def factorize(n):
    """Factorize a number into prime factors."""
    factors = []
    while n > 1:
        factor = pollard_rho(n)
        while n % factor == 0:
            factors.append(factor)
            n //= factor
    return factors


def main():
    """Read a number from a file and factorize it."""
    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
        sys.exit(1)

    filename = sys.argv[1]
    try:
        with open(filename, 'r') as file:
            num = int(file.readline())
            factors = factorize(num)
            print("{}=".format(num), end="")
            print("*".join(map(str, factors)), end="")
            print()
    except FileNotFoundError:
        print("File not found:", filename)
        sys.exit(1)
    except ValueError:
        print("Invalid number in file")
        sys.exit(1)


if __name__ == "__main__":
    main()
